# Generated by Django 4.2.7 on 2023-12-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_house_room_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
    ]
