# Generated by Django 4.2.8 on 2024-01-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_installer'),
    ]

    operations = [
        migrations.AddField(
            model_name='installer',
            name='devices',
            field=models.IntegerField(null=True),
        ),
    ]
