# Generated by Django 4.2.7 on 2023-12-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_device_mac_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='mac_address',
        ),
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
                ('device_password', models.CharField(max_length=255)),
                ('network_ssid', models.CharField(max_length=255)),
                ('network_password', models.CharField(max_length=255)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.device')),
            ],
        ),
    ]
