# Generated by Django 4.2.8 on 2024-01-10 04:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_installer_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('join_time', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('join_time', models.DateField(default=django.utils.timezone.now)),
                ('super_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.superadmin')),
            ],
        ),
        migrations.AddField(
            model_name='installer',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.admin'),
        ),
    ]
