# Generated by Django 4.2.7 on 2023-12-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_device_mac_address_deviceconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfiguration',
            name='current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceconfiguration',
            name='device_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deviceconfiguration',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceconfiguration',
            name='power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceconfiguration',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deviceconfiguration',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceconfiguration',
            name='voltage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
