# Generated by Django 4.2.8 on 2024-01-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_superadmin_admin_installer_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.CharField(default='ADMIN'),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='role',
            field=models.CharField(default='SUPERADMIN'),
        ),
    ]
