# Generated by Django 4.2.7 on 2023-12-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_deviceconfiguration_current_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceconfiguration',
            old_name='device_name',
            new_name='device_names',
        ),
    ]
