# Generated by Django 4.2.8 on 2024-01-10 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_admin_role_superadmin_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='join_time',
        ),
        migrations.AddField(
            model_name='admin',
            name='join_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
