# Generated by Django 4.2.8 on 2024-01-10 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_admin_join_date_remove_admin_join_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installer',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='installer',
            name='join_time',
        ),
        migrations.AddField(
            model_name='installer',
            name='join_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
