# Generated by Django 4.2.7 on 2023-12-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_deviceconfiguration_device_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfiguration',
            name='device_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
