# Generated by Django 4.2.8 on 2024-01-10 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_installer_join_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installer',
            old_name='devices',
            new_name='users',
        ),
    ]
