# Generated by Django 4.2.8 on 2024-01-10 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_devices_installer_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='installer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.installer'),
        ),
    ]
