# Generated by Django 4.2.7 on 2023-12-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
