# Generated by Django 4.2.7 on 2023-12-11 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_device_user_deviceconfiguration_user_room_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='join_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
