# Generated by Django 4.2.7 on 2023-12-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_join_date_user_join_time_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacIpMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
