# Generated by Django 5.0 on 2023-12-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_macipmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceconfiguration',
            name='mac_address',
        ),
        migrations.AddField(
            model_name='device',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
