# Generated by Django 5.0 on 2023-12-22 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_devicedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedata',
            name='device',
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='user',
        ),
    ]
