# Generated by Django 5.0 on 2023-12-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_devicedata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='status',
            field=models.IntegerField(),
        ),
    ]
