# Generated by Django 5.0 on 2023-12-29 04:33

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_device_mac_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceconfiguration',
            name='network_password',
        ),
        migrations.RemoveField(
            model_name='deviceconfiguration',
            name='network_ssid',
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_ssid', models.CharField(max_length=255)),
                ('network_password', models.CharField(max_length=255)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=users.models.upload_to)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
