# Generated by Django 5.0 on 2023-12-29 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_userprofile_delete_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
